local_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.25 # 0.25 seconds of latency, if greater than this, planner will stop
  static_map: true
  rolling_window: true # Follow robot while navigating
  width: 3
  height: 3
  origin_x: -1.5
  origin_y: -1.5
  resolution: 0.05
  inflater_layer:
    inflation_radius: 0.2
    cost_scaling_factor: 1.0
 
  # Add other local costmap parameters here

  

